### ISSUE TITLE
Trouble with CSS background color

### ISSUE THREAD

**Issue by Dnash1** [Dnash1/projTwo#1]
Pure is not wanting to take the background color from the stylesheet. Takes everything else, but I've tried setting background-color on both body and html to no effect.

`html, body {
    background-color: black;
    color: black;
}`

Is this a known issue?

**Comment by Dnash1** [comment]
Alright, on further inspection it's not loading the CSS at all. I may be having a similar problem to Heather's but I thought I was doing what she did.
`<link rel="stylesheet" href="./styles.css">
app.use(express.static('public'));`

Styles is in the public directory.

**Comment by Dnash1** [comment]
Ok... so it is finding the .css file. Just none of the styles are actually going in...

**Comment by Dnash1** [comment]
Problem resolved. The nature of the problem was that I am retarded and was editing a different file.

_waves hand_ You saw nothing.

**Comment by andrewfritz86** [comment]
Hahahahahha

**Comment by andrewfritz86** [comment]
Losing it here
